###Register User
POST http://localhost:1000/user/register/
Content-Type: application/json

{
    "firstName": "Ngatia",
    "lastName": "Mwai",
    "email": "mwai4@gmail.com",
    "phoneNumber": "1234567",
    "password": "123456789"
}


###Login User/Thunder Client
GET http://localhost:1000/user/login
Content-Type: application/json

{
    "email": "mwai4@gmail.com",
    "password": "123456789"
}

###All users
GET http://localhost:1000/user/allusers



###update /Thunder Client
POST http://localhost:1000/user/update/66d7cbe9-80d7-4870-a96a-90edc6510dd2
Content-Type: : application/json
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YjI5YWU1ZS03YzU1LTQ3YzItODcyNC01MjUzZjQzODFlMTciLCJmaXJzdE5hbWUiOiJOZ2F0aWEiLCJsYXN0TmFtZSI6Ik13YWkiLCJlbWFpbCI6Im13YWk0QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA1JEFXd1VVZDk2UHY4eVc3eDkxRnhvek9mWEkxQ0ZidWxNTkJJMkgyTXdRVXI0cG9tUVVaeDlhIiwicGhvbmVOdW1iZXIiOiIxMjM0NTY3IiwicmVnaXN0cmF0aW9uRGF0ZSI6IjIwMjMtMTAtMTFUMTE6MjI6MzUuNjA3WiIsImlhdCI6MTY5NzAxMjYwNCwiZXhwIjoxNjk3MDQ4NjA0fQ.9ExW9iQDMifwBbB_naDc_I_V7SS74LAHoCFzx5R5rMQ

{
    "firstName": "Ngatia3",
    "lastName": "Mwai3",
    "email": "mwai5@gmail.com",
    "phoneNumber": "12345678",
}


###Get one user
GET http://localhost:1000/user/oneuser/12bd3095-d88a-4340-bf1e-e7975195a168
Content-Type: application/json


###Delete user
DELETE  http://localhost:1000/user/deleteuser/a14389fc-a558-434a-9ccd-ed10ca0cd4a4
Content-Type: application/json


###Create product
POST http://localhost:1000/products/newproduct/
Content-Type: application/json

{
    "productName": "Mazda",
    "productDescription": "The best Mazda in the market",
    "productPrice": "7000000",
    "productCategory": "car",
    "productImage": "123456789",
    "productNum":"23"
}


###Get all products
GET http://localhost:1000/products/allproducts/
Content-Type: application/json




###Get one product
GET http://localhost:1000/products/oneproduct/5a4bc3de-1523-4f1a-a548-fec8d5647e4f
Content-Type: application/json



###Update product/updating but sending a wrong message
POST http://localhost:1000/products/updateproduct/4d162ae0-0261-43b5-b413-9b36e1422705
Content-Type: application/json

{
    "productName": "Shuka",
    "productDescription": "The best shuka in the market",
    "productPrice": "3000",
    "productCategory": "Fashion",
    "productImage": "productImage"
}


###Delete product
DELETE  http://localhost:1000/products/deleteproduct/5a4bc3de-1523-4f1a-a548-fec8d5647e4f
Content-Type: application/json



###Add product To cart
POST http://localhost:1000/cart/addtocart/12bd3095-d88a-4340-bf1e-e7975195a168/4d162ae0-0261-43b5-b413-9b36e1422705
Content-Type: application/json



###your cart
GET http://localhost:1000/cart/yourcart/12bd3095-d88a-4340-bf1e-e7975195a168/
Content-Type: application/json



###Remove product from cart
DELETE http://localhost:1000/cart/removefromcart/f0ddfba6-5180-42ad-9a65-30baded30ef4
Content-Type: application/json

